#!/usr/bin/env node

const { generateOpenAPISchema } = require('../dist/ycard-schema');
const yaml = require('js-yaml');
const fs = require('fs');

const spec = generateOpenAPISchema();

const commentBlock = `# =============================================================================
# yCard OpenAPI Schema - AUTO-GENERATED FILE
# =============================================================================
#
# ⚠️  WARNING: This file is automatically generated from the Zod schema!
# ⚠️  DO NOT EDIT THIS FILE MANUALLY - your changes will be lost!
#
# This OpenAPI specification is generated from the TypeScript Zod schema
# located in src/ycard-schema.ts. It contains type definitions for yCard data
# structures including all supported aliases and internationalization fields.
#
# To regenerate this file after making changes to the Zod schema:
#   1. Make your changes to src/ycard-schema.ts
#   2. Run: npm run generate-openapi
#   3. This file will be automatically updated
#
# For more information, see the README.md file in the project root.
# =============================================================================

`;

fs.writeFileSync('openapi.yaml', commentBlock + yaml.dump(spec, { indent: 2 }));
console.log('Generated openapi.yaml from Zod schema');
